language: objective-c  #1
osx_image: xcode7.2 #2
rvm:
  - 2.2.2

xcode_workspace: RXTreeControl.xcworkspace #3
xcode_scheme: RXTreeControl #4
xcode_sdk: iphonesimulator9.1
xcode_sdk: iphoneos9.2

before_install: gem install cocoapods -v '= 0.39.0'
#script: "rake run:ios"

#script: "rake test:ios"